#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#include "keymap.h"
#endif


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, TO(4), KC_MUTE, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RBRC, KC_LGUI, KC_SPC, KC_ENT, MO(1), KC_LALT, KC_SPC, MO(2), KC_RSFT, KC_RALT, KC_RALT),
    [1] = LAYOUT(LALT(KC_F4), KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_NO, KC_NO, LCTL(KC_BSPC), KC_UP, LCTL(KC_DEL), KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_F12, LCTL(KC_Y), KC_BSPC, KC_LEFT, KC_DOWN, KC_RGHT, KC_DEL, KC_NO, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_NO, KC_NO, LCTL(KC_LEFT), LCTL(KC_F10), LCTL(KC_RGHT), KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), KC_0, KC_NO, KC_NO),
    [2] = LAYOUT(KC_NO, RALT(KC_1), RALT(KC_2), RALT(KC_3), RALT(KC_4), RALT(KC_5), RALT(KC_6), RALT(KC_7), RALT(KC_8), RALT(KC_9), RALT(KC_F10), RALT(KC_F11), LSFT(KC_GRV), RALT(KC_Q), LSFT(KC_NUHS), RALT(KC_E), KC_NO, KC_NO, KC_NO, RALT(KC_7), RALT(KC_8), RALT(KC_9), RALT(KC_0), RALT(KC_F12), KC_GRV, LSFT(KC_1), LSFT(KC_2), LSFT(KC_3), LSFT(KC_4), LSFT(KC_5), LSFT(KC_6), LSFT(KC_7), LSFT(KC_8), LSFT(KC_9), LSFT(KC_0), KC_NUHS, RALT(KC_NUBS), KC_NUBS, LSFT(KC_NUBS), KC_EQL, LSFT(KC_EQL), KC_NO, KC_NO, KC_NO, KC_NO, RALT(KC_MINS), KC_NO, LSFT(KC_MINS), RALT(KC_RBRC), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO),
    [3] = LAYOUT(TO(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO),
    [4] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_T, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_Z, KC_U, KC_I, KC_O, KC_P, KC_SCLN, KC_G, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LCTL, KC_LCTL, KC_Y, KC_X, KC_C, KC_V, TO(0), KC_TRNS, KC_N, KC_M, KC_COMM, KC_DOT, KC_MINS, KC_EQL, KC_F16, KC_F17, KC_B, KC_LALT, KC_SPC, TO(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};

#if defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [0] = { ENCODER_CCW_CW(TO(0), TO(4)) },
    [1] = { ENCODER_CCW_CW(TO(0), TO(4)) },
    [2] = { ENCODER_CCW_CW(TO(0), TO(4)) },
    [3] = { ENCODER_CCW_CW(TO(0), TO(4)) },
    [4] = { ENCODER_CCW_CW(TO(0), TO(4)) }
};
#endif



